# Generated by Django 5.1.3 on 2025-12-28 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='receipts.receipt'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa rozliczenia')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('join_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('members', models.ManyToManyField(related_name='settlements', to=settings.AUTH_USER_MODEL, verbose_name='Członkowie')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.settlement'),
        ),
    ]
