# Generated by Django 5.1.3 on 2025-12-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_settlement_created_at_settlement_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='receipts.settlement', verbose_name='Przypisane rozliczenie'),
        ),
    ]
