# Generated by Django 5.1.3 on 2025-12-28 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_product_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consumers',
            field=models.ManyToManyField(blank=True, related_name='consumed_products', to=settings.AUTH_USER_MODEL, verbose_name='Konsumenci'),
        ),
    ]
