# Generated by Django 5.1.3 on 2025-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_product_consumers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Jedzenie'), ('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Nocleg'), ('ENTERTAINMENT', 'Rozrywka'), ('SHOPPING', 'Zakupy'), ('SERVICES', 'Usługi'), ('OTHER', 'Inne')], default='OTHER', max_length=20, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Jedzenie'), ('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Nocleg'), ('ENTERTAINMENT', 'Rozrywka'), ('SHOPPING', 'Zakupy'), ('SERVICES', 'Usługi'), ('OTHER', 'Inne')], default='OTHER', max_length=20, verbose_name='Kategoria'),
        ),
    ]
