# Generated by Django 5.1.3 on 2026-01-06 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_product_price_alter_receipt_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name': 'Rozliczenie', 'verbose_name_plural': 'Rozliczenia'},
        ),
        migrations.AlterField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='receipts.receipt', verbose_name='Paragon'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Obraz'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Kupujący'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.settlement', verbose_name='Rozliczenie'),
        ),
    ]
