# Generated by Django 5.1.3 on 2026-01-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_product_description_receipt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Ilość'),
        ),
    ]
