# Generated by Django 5.1.3 on 2026-01-15 17:54

import receipts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='join_code',
            field=models.CharField(default=receipts.models.generate_join_code, editable=False, max_length=6, unique=True),
        ),
    ]
