# Generated by Django 5.1.3 on 2026-01-16 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0014_receipt_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='owner',
        ),
        migrations.AddField(
            model_name='settlement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_settlements', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
    ]
