# Generated by Django 5.1.3 on 2026-01-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_remove_receipt_owner_settlement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='receipts.receipt', verbose_name='Paragon'),
        ),
    ]
