# Generated by Django 5.1.3 on 2026-01-17 21:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0016_alter_product_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota')),
                ('settled_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wykonania')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_from_user', to=settings.AUTH_USER_MODEL, verbose_name='Od użytkownika')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_settlements', to='receipts.settlement', verbose_name='Rozliczenie')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Do użytkownika')),
            ],
            options={
                'verbose_name': 'Wykonane rozliczenie',
                'verbose_name_plural': 'Wykonane rozliczenia',
                'ordering': ['-settled_at'],
            },
        ),
    ]
